version: "2"
services:
  openmrs-mysql-db:
    image: mysql:5.6
    container_name: &db openmrs-mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: shr
      MYSQL_USER: &openmrs_db_user admin
      MYSQL_PASSWORD: &openmrs_db_password Admin123
    volumes:
      - openmrs-mysqldata:/var/lib/mysql

  postgresql-openxds:
    container_name: postgresql-openxds
    image: uwitech/postgresql
    ports:
      - 5433:5432
    volumes:
      - openxds-pgdata:/var/lib/postgresql/data

  openxds:
    container_name: openxds
    image: uwitech/openxds
    ports:
      - "8010:8010"
      - "8020:8020"
    depends_on:
      - postgresql-openxds

  openmrs:
    image: uwitech/oshr
    ports:
      - "8090:8080"
    container_name: openmrs-platform
    depends_on:
      - openmrs-mysql-db
      - openxds
    environment:
      MYSQL_ROOT_PASSWORD: shr
      MYSQL_USER: *openmrs_db_user
      MYSQL_PASSWORD: *openmrs_db_password
      MYSQL_HOST: *db
      MYSQL_PORT: 3306
      OPENMRS_DATABASE: openmrs

volumes:
  openxds-pgdata:
  openmrs-mysqldata:
